language: objective-c	# Even though this project is in Swift
xcode_project: BottomSheetViewController.xcodeproj
xcode_scheme: BottomSheetViewController
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.2
